### PR TITLE
Convert to LibLog from ILogger

### PR DESCRIPTION
**Pull request by madhon**
Converts to using LibLog for transparent support of whatever logging library the host application is using instead of having to define a logger to match the ILogger interface.

https://github.com/damianh/LibLog/wiki

### CODE REVIEW

**Comment by judwhite** [comment]
Thanks, I do like the idea of not passing an ILogger around.

Let's say someone imports a library which has a hard dependency on Log4Net, another library uses Common.Logging, and in their application code they decided to use NLog. How does LibLog behave in this scenario?

**Comment by madhon** [comment]
Liblog just uses whatever has been registered in the starting application, in this case I think it would use nlog.

Sent via mobile

**Comment by judwhite** [comment]
Thanks, I'll play with it a bit. My main concern is avoiding magic because it's hard to debug when things go wrong.

Cross-cutting concerns should be transparent. That was my original thinking when defaulting the optional ILogger parameters to [TraceLogger](https://github.com/judwhite/NsqSharp/blob/master/NsqSharp/Utils/Loggers/TraceLogger.cs) and just letting the logger du jour register a TraceListener.

As a side note it looks like there's a [MassTransit.LibLog](https://github.com/robinvanderknaap/MassTransit.LibLog) plugin. It looks like they took a hybrid approach.

I'll look into it some more, I'm working on some hardening at the moment which may take some time. Thanks again!

**Comment by judwhite** [comment]
Hi @madhon,

I think the [default](https://github.com/judwhite/NsqSharp/blob/c2c2b185837470f6eb247c85438f39078b35e471/NsqSharp/Bus/Configuration/BusConfiguration.cs#L87) [TraceLogger](https://github.com/judwhite/NsqSharp/blob/master/NsqSharp/Utils/Loggers/TraceLogger.cs) accomplishes logging package independence in a standard way. Most logging frameworks feature a [TraceListener](https://msdn.microsoft.com/en-us/library/4y5y10s7%28v=vs.110%29.aspx) which can filter on the TraceSource.

If [ILogger](https://github.com/judwhite/NsqSharp/blob/master/NsqSharp/Core/ILogger.cs) was removed and you wanted to perform a custom action, such as forwarding errors to an external service, sending email, or writing something custom to the event log, you'd need to hook into your logging framework if it supports hooks. Allowing the user to specify an implementation allows more control when needed while still providing the convenience of writing to a TraceSource for simple scenarios.

There's also the issue of future proofing. What if a new logging framework comes out but we're stuck only supporting a few? What if I already wrote a custom logging framework, how could I use my custom logger? A lot of projects/companies wrap one of the standard logging frameworks to enrich the data with other contextual information or perform custom actions, such as Event Log writing or alerting.

A few other notes
- Removing the `log` method from Consumer and Producer, and removing the call to `SetLogger` on Conn, removed the Consumer / Producer ID, topic, and channel from the log output.
- Changing the formatting makes diff'ing difficult even with `?w=1`.

I would like help implementing structured logging. See [logrus](https://github.com/Sirupsen/logrus) for an example implementation and [logfmt](https://brandur.org/logfmt) as one possible format. On the C# side there's [Serilog](https://github.com/serilog/serilog) (supported by LibLog) which looks very close to what I'm looking for.

Thanks again for the PR and sorry it took so long to get back to you.

**Pull request closed without merging**
