### PR TITLE
Autofac support

### PR DESCRIPTION
**Pull request by judwhite**
/cc @crazybert
- [x] Move more reflection code into the `AutofacObjectBuilder` constructor
- [x] Feedback on approach

### CODE REVIEW

**Comment by crazybert** [comment]
I'd recommend separating Configuration and Activation as different concerns, but it seems like it'd require interface changes.

**Comment by judwhite** [comment]
Some work needs to be done to tighten up the reflection code into the `AutofacObjectBuilder` constructor and keep it light in `GetInstance` and `Inject`.

Couple of things the consider:
- I didn't want to call `Build` on a `ContainerBuilder`.
- You have to pass an already built `IContainer` to the `AutofacObjectBuilder` constructor.
- Currently I'm injecting into the already built `IContainer` at bus start to register `IBus` and `IHandleMessages<>` implementations. Is there another approach that might be better, such as using a subcontainer? If so what would the benefits be?

**Comment by crazybert** [comment]
IBus bus = BusService.ConfigrureBus(BusConfiguration);
IContainer c = ContainerBuilder.Build();
bus.SetDependencyResolver(new AutofacDependencyResolver(container));
bus.Start();

**Comment by judwhite** [comment]
That would be a pretty big breaking change for existing apps.

**Comment by crazybert** [comment]
Not really. 
-Make IObjectBuilder optional. If it is not provided - skip Inject call().
-Add ConfigureBus which will not call Start()
-Add SetDependencyResolver()
-Expose Start()

This should be backward compatible.

**Comment by judwhite** [comment]
I'd probably take the opportunity to revisit how the bus is initialized/started and leave the existing implementation with an `[Obsolete]` attribute if a better but incompatible pattern comes out of it. This might be necessary for running the bus in w3wp anyway. I'm not ready to make this change yet, I want to make sure it's thought through.

I can't make `IObjectBuilder` optional without making every other parameter optional since it's first in the list. I could make it accept `null` but that'd require refactoring like the above which I want to wait on.

One approach I tried was adding a `Build` method to `IObjectBuilder`, it'd be a no-op for StructureMap and solve the direct injection for Autofac. I didn't think it'd be appropriate to call Autofac's `Build` though.

Another thing which could be tried is provide a callback for when the library is done injecting types into the container builder. You could do any final work needed (such as call `Build`). The remaining problem is you'd have to pass this back to the bus somehow for it to now use the container. -- Thinking about this some more this is essentially what the `Build` method on `IObjectBuilder` did.

Do you need to call `Build` after passing it to the bus or are you trying to clean up the injection into an already built container?

Does the current approach work in your code?

**Comment by crazybert** [comment]
I am concerned about using reflection and calling methods which are not supposed to be called. Really :-)

**Comment by judwhite** [comment]
They're all `public` methods. This is also how [`StrucutreMapObjectBuilder`](https://github.com/judwhite/NsqSharp/blob/master/NsqSharp/Bus/Configuration/BuiltIn/StructureMapObjectBuilder.cs) and [`NewtonsoftJsonSerializer`](https://github.com/judwhite/NsqSharp/blob/master/NsqSharp/Bus/Configuration/BuiltIn/NewtonsoftJsonSerializer.cs) work. Reflection is the only option without taking a direct dependency, or implement `IObjectBuilder` in your code.

**Pull request merged**
